import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menubar from "./components/Menubar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scars of Fate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-[95vw] mt-2 xl:max-w-[1360px] w-full h-full">
          <div className="bg-slate-800/90 text-slate-200 p-6 rounded-lg">
            <Menubar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
